### ISSUE TITLE
More statistically accurate score?

### ISSUE THREAD

**Issue by fbessho** [miyagawa/Tabelog-HonestStars#1]
The conversion map looks so rough to me.
Should 2.9 and 1.0 be the same score? (Perhaps not?) Should 4.1 and 4.8 be? (well.. maybe they should be the same score.)

Do you have plan to improve your conversion map to more.. accurate for example using a statistical method?
I think it's also true that it's not required or even worse to have such a high granularity as it impairs user experience?

Any thought?

**Comment by miyagawa** [comment]
No, they have to be the same score because that's the whole point.
